package com.example.domain.model

object GameRegistry {
    val games = listOf(
        GameDef(
            id = "symbol_reader",
            title = "Symbol Mind Reader",
            category = GameCategory.MIND_READING,
            difficulty = Difficulty.EASY,
            description = "A classic mind-reading trick where the app divines your secret symbol from a chosen two-digit number.",
            instructions = "1. Think of any two-digit number (e.g., 54).\n2. Subtract the sum of its digits from your number (e.g., 54 - (5 + 4) = 45).\n3. Find your resulting number on the grid and look at its symbol.\n4. Focus on the symbol, click 'Read My Mind', and the wizard will reveal it!",
            durationMinutes = 2,
            concept = "Algebraic Invariants and Multiples of 9",
            tags = listOf("Invariants", "Algebra", "Mind Reading"),
            history = "The Symbol Mind Reader is a classic mathematical parlor trick that has circulated on the early internet. It relies on a mathematical invariant that maps any two-digit number to a multiple of 9 after subtracting its digits.",
            realWorldApps = "Digital checksums, parity bits in computer memory, and barcode verification algorithms use similar digit-sum invariants to detect transmission errors."
        ),
        GameDef(
            id = "emoji_reader",
            title = "Emoji Mind Reader",
            category = GameCategory.MIND_READING,
            difficulty = Difficulty.EASY,
            description = "A friendly emoji variation of the multiple-of-9 mind reader. The universe speaks in emojis!",
            instructions = "1. Pick any two-digit number (e.g., 83).\n2. Subtract its digits from it (e.g., 83 - 8 - 3 = 72).\n3. Find the corresponding emoji in the grid.\n4. Concentrate on that emoji and click 'Concentrate' to let the emoji wizard reveal your mind!",
            durationMinutes = 2,
            concept = "Sub-nine Divisibility Invariance",
            tags = listOf("Emojis", "Divisibility", "Arithmetic"),
            history = "An aesthetic evolution of the grid-based mathematical puzzle designed to make algebra intuitive and engaging for all age groups.",
            realWorldApps = "Hashing functions in database indexing use modulo and arithmetic folding similar to this trick to evenly distribute keys."
        ),
        GameDef(
            id = "binary_guess",
            title = "Binary Number Guess",
            category = GameCategory.MIND_READING,
            difficulty = Difficulty.MEDIUM,
            description = "Pick a secret number from 1 to 63. Point out which of the six cards contain your number, and we will reveal it!",
            instructions = "1. Think of a secret number between 1 and 63.\n2. We will show you 6 cards one by one.\n3. Tap 'Yes' if your number is on the card, or 'No' if it is not.\n4. At the end, the exact number you imagined will be revealed!",
            durationMinutes = 3,
            concept = "Binary Radix Base-2 Representation",
            tags = listOf("Binary", "Radix", "Computer Math"),
            history = "This trick dates back to early computational mathematics demonstrations. It is often called the 'Window Card Trick' or 'Leibniz's Cards', named after Gottfried Wilhelm Leibniz, who co-invented binary arithmetic.",
            realWorldApps = "All modern electronic circuits, microprocessors, IP routing, and cryptography are built entirely on binary representation (bits 0 and 1)."
        ),
        GameDef(
            id = "age_guesser",
            title = "Age Guesser Wizard",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.EASY,
            description = "Let the math wizard guess your age! Perform simple arithmetic calculations, and the wizard will show how reverse equations find your secret.",
            instructions = "1. Imagine your current age (or any secret number from 1 to 99).\n2. Multiply it by 3.\n3. Add 6 to the result.\n4. Divide the result by 3.\n5. Tell us the final calculated value, and we will instantly reverse-engineer your age!",
            durationMinutes = 2,
            concept = "Inverse Functions and Reversible Operations",
            tags = listOf("Algebra", "Reversible Arithmetic", "Functions"),
            history = "Reversible arithmetic puzzles have been featured in math publications since the Middle Ages. They demonstrate the concept of bijection—where every input maps to exactly one unique output.",
            realWorldApps = "Symmetric key cryptography algorithms (like AES) rely on highly complex reversible mathematical functions to encrypt and decrypt data."
        ),
        GameDef(
            id = "birthday_guesser",
            title = "Birthday Guesser",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.MEDIUM,
            description = "Perform a series of arithmetic steps on your birth month and day, and the wizard will tell you your exact birthday!",
            instructions = "1. Take your birth month number (1 for Jan, 12 for Dec).\n2. Multiply it by 5.\n3. Add 7.\n4. Multiply by 4.\n5. Add 13.\n6. Multiply by 5.\n7. Add your birth day (1 to 31).\n8. Enter your final total below to let the wizard decode your birthday!",
            durationMinutes = 3,
            concept = "Linear Diophantine Combinations",
            tags = listOf("Algebra", "Decoders", "Linear Equations"),
            history = "First popularized by recreational mathematicians in the 19th century, this trick demonstrates how base offsets can be hidden behind linear equations.",
            realWorldApps = "Parsing structured data packets in network protocols, where multi-part coordinates are packed into a single integer."
        ),
        GameDef(
            id = "calendar_prediction",
            title = "Calendar Predictor",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.EASY,
            description = "Select any 3x3 block of dates on a calendar grid. We will immediately predict the exact sum of all 9 dates!",
            instructions = "1. Click on a date to center a 3x3 box on a calendar month.\n2. The app will immediately predict the sum of all nine dates.\n3. Manually add them up to verify the prediction. It is 100% correct!",
            durationMinutes = 2,
            concept = "Arithmetic Progressions and Centroid Sums",
            tags = listOf("Calendar", "Progressions", "Symmetry"),
            history = "Calendar tricks highlight the inherent symmetries in grid-based coordinate systems. Because calendar rows are offsets of 7, they form highly structured arithmetic progressions.",
            realWorldApps = "Digital signal processing, where 2D matrix convolution kernels (like Gaussian blur) compute cell values using neighboring cell offsets."
        ),
        GameDef(
            id = "trick_1089",
            title = "The Magic 1089 Trick",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.MEDIUM,
            description = "The famous 1089 trick. No matter what three-digit number you choose, the final mathematical result is always 1089!",
            instructions = "1. Choose a 3-digit number where the first and last digits differ by at least 2 (e.g., 725).\n2. Reverse the digits (527) and subtract the smaller from the larger (725 - 527 = 198).\n3. Reverse the result (891) and add it to the subtraction result (198 + 891).\n4. Watch the magic sum reveal itself!",
            durationMinutes = 3,
            concept = "Base-10 Algebraic Expansion and Simplification",
            tags = listOf("1089", "Place Value", "Algebra"),
            history = "This trick is a staple of recreational mathematics and is described in David Acheson's book '1089 and All That'. It is an elegant proof of how positional subtraction eliminates arbitrary choices.",
            realWorldApps = "Diffie-Hellman Key Exchange uses algebraic groups to ensure that independent steps always converge to a shared secret key."
        ),
        GameDef(
            id = "kaprekar_constant",
            title = "Kaprekar's Constant (6174)",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.MEDIUM,
            description = "Enter any 4-digit number (with at least two distinct digits). Sort and subtract repeatedly. You will always converge to the black hole constant: 6174!",
            instructions = "1. Enter a 4-digit number with at least two distinct digits (e.g., 3524).\n2. Rearrange its digits to make the largest (5432) and smallest (2345) numbers possible.\n3. Subtract the smallest from the largest.\n4. Repeat the process with the result and watch how quickly it collapses to 6174!",
            durationMinutes = 3,
            concept = "Kaprekar Routine and Attractor States",
            tags = listOf("6174", "Attractors", "Number Theory"),
            history = "Discovered in 1949 by Indian mathematician D. R. Kaprekar, this routine reveals one of the most famous numeric attractors (fixed points) in decimal mathematics.",
            realWorldApps = "Chaos theory, dynamical systems, and neural networks, which seek attractor states where noisy inputs stabilize into standard outputs."
        ),
        GameDef(
            id = "digital_root",
            title = "Digital Root Explorer",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.EASY,
            description = "Explore the magical digital root of any number by repeatedly summing its digits until a single digit remains.",
            instructions = "1. Enter any large integer of your choice.\n2. The app will repeatedly sum its digits in a step-by-step animation.\n3. Learn why the digital root is equivalent to the remainder when dividing the number by 9 (modulo 9)!",
            durationMinutes = 2,
            concept = "Digital Roots and Modulo 9 Arithmetic",
            tags = listOf("Modulo", "Digital Root", "Arithmetic"),
            history = "Digital roots have been used in Vedic Mathematics for thousands of years under the name 'Navashesa'. They are deeply tied to divisibility rules.",
            realWorldApps = "Hash generation, checksums (like the Luhn Algorithm on credit cards), and simple digital filters."
        ),
        GameDef(
            id = "casting_nines",
            title = "Casting Out Nines",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.MEDIUM,
            description = "Learn and practice the ancient technique of checking arithmetic calculations using digital roots.",
            instructions = "1. Select an arithmetic equation (addition or multiplication).\n2. Calculate the digital root of each operand and of the result.\n3. If the digital roots match under the operator, the math is verified! Test it yourself.",
            durationMinutes = 3,
            concept = "Congruence Relations modulo 9",
            tags = listOf("Arithmetic", "Verification", "Congruence"),
            history = "Dating back to Greek mathematician Nicomachus (100 AD) and medieval Arab scholars, this technique allowed accountants to verify long ledgers before calculators existed.",
            realWorldApps = "Cyclic Redundancy Checks (CRCs) in network packet headers use polynomial division over finite fields (similar to mod 9 checks) to verify packet integrity."
        ),
        GameDef(
            id = "magic_square",
            title = "Magic Square Generator",
            category = GameCategory.NUMBER_MAGIC,
            difficulty = Difficulty.HARD,
            description = "Generate a perfect 4x4 Magic Square where every row, column, diagonal, and 2x2 quadrant sums to your chosen secret target number!",
            instructions = "1. Enter a secret target sum (must be 34 or greater).\n2. The app will instantaneously generate a highly symmetrical 4x4 grid of numbers.\n3. Highlight different rows, diagonals, or corners to verify they all sum exactly to your target!",
            durationMinutes = 4,
            concept = "Linear Transformations and Matrix Symmetries",
            tags = listOf("Matrix", "Magic Square", "Linear Algebra"),
            history = "The 4x4 magic square is famous from Albrecht Dürer's 1514 engraving 'Melencolia I'. It is one of the oldest mathematical art pieces in Western history.",
            realWorldApps = "Sudoku generation, cryptography permutation matrices, and spatial block coding in telecommunications."
        ),
        GameDef(
            id = "monty_hall",
            title = "Monty Hall Simulator",
            category = GameCategory.PROBABILITY,
            difficulty = Difficulty.MEDIUM,
            description = "Play the famous game show! Pick a door, the host reveals a goat behind another, and you decide whether to switch. Run simulations to witness the ultimate statistical mind-bender.",
            instructions = "1. Tap one of the three doors to make an initial selection.\n2. The host (Monty) will open one of the remaining doors to show a goat.\n3. Choose whether to STAY with your initial pick, or SWITCH to the other closed door.\n4. Run the auto-simulator to perform 1,000 games and observe the actual switch vs. stay win rates!",
            durationMinutes = 4,
            concept = "Conditional Probability and Bayes' Theorem",
            tags = listOf("Probability", "Simulations", "Bayes"),
            history = "Based on the American television show 'Let's Make a Deal', this paradox was famously solved by Marilyn vos Savant in her column, causing thousands of PhD mathematicians to initially write angry letters disagreeing with her correct solution.",
            realWorldApps = "Decision-making trees, clinical trials, search algorithms, and machine learning models predicting outcomes given partial evidence."
        ),
        GameDef(
            id = "birthday_paradox",
            title = "Birthday Paradox Lab",
            category = GameCategory.PROBABILITY,
            difficulty = Difficulty.MEDIUM,
            description = "Simulate shared birthdays in a room. Discover why it only takes 23 people for a 50% chance of a shared birthday, and 57 people for 99%!",
            instructions = "1. Adjust the slider to set the number of people in the room.\n2. Run a real-time simulation of random birthdays.\n3. Look at the colored graph to see how actual statistical collisions compare to theoretical probability calculations.",
            durationMinutes = 4,
            concept = "Complementary Probability and Combinatorics",
            tags = listOf("Combinatorics", "Paradox", "Collisions"),
            history = "First identified by Richard von Mises in 1939, this paradox shows how poorly the human mind estimates exponential combinations.",
            realWorldApps = "Hash collisions in cyber security (called 'Birthday Attacks') exploit this mathematical concept to force cryptographic key collisions."
        ),
        GameDef(
            id = "dice_prediction",
            title = "Dice Prediction Trick",
            category = GameCategory.MIND_READING,
            difficulty = Difficulty.MEDIUM,
            description = "Roll three imaginary dice. Follow calculations in your head, and the app will decipher all three dice values perfectly!",
            instructions = "1. Imagine throwing 3 standard dice (e.g., Die A, Die B, Die C).\n2. Multiply the face value of Die A by 2, and add 5.\n3. Multiply the result by 5, and add the value of Die B.\n4. Multiply the result by 10, and add the value of Die C.\n5. Enter the final number below, and watch the app decode all three dice!",
            durationMinutes = 3,
            concept = "Positional Algebra and Base Decoding",
            tags = listOf("Dice", "Positional Value", "Arithmetic"),
            history = "A classic mentalism effect demonstrating how base-10 numerical packing is achieved through nested algebraic multipliers.",
            realWorldApps = "Bit packing in binary files, where multiple separate variables are packed into a single byte stream to save memory."
        ),
        GameDef(
            id = "coin_probability",
            title = "Coin Probability Lab",
            category = GameCategory.PROBABILITY,
            difficulty = Difficulty.EASY,
            description = "Simulate thousands of coin flips in seconds. Watch the experimental ratio converge to the theoretical 50% limit.",
            instructions = "1. Tap 'Flip 1' or 'Simulate 1000' to flip coins.\n2. Watch the real-time line chart plot the running head-to-tail ratio.\n3. Experience the law of large numbers as the graph flattens precisely towards 0.50.",
            durationMinutes = 3,
            concept = "Law of Large Numbers and Bernoulli Processes",
            tags = listOf("Flips", "Stochastics", "Convergence"),
            history = "Articulated by Jacob Bernoulli in 1713, this theorem forms the absolute mathematical foundation of modern probability and mathematical statistics.",
            realWorldApps = "Insurance underwriting, statistical sampling, financial risk analysis, and gaming design."
        ),
        GameDef(
            id = "nim_game",
            title = "The Game of Nim",
            category = GameCategory.LOGIC,
            difficulty = Difficulty.HARD,
            description = "Play the ancient game of Nim against an unbeatable AI! Take turns removing items from multiple heaps. Can you beat the mathematical XOR engine?",
            instructions = "1. You and the AI take turns.\n2. On your turn, select one heap and remove any number of items (at least 1) from it.\n3. The player who takes the very last item of the game wins.\n4. Can you find a winning strategy, or will the XOR-powered AI master you?",
            durationMinutes = 5,
            concept = "Bouton's Theorem and Nim-Sum XOR Logic",
            tags = listOf("Game Theory", "XOR", "AI"),
            history = "Nim is an ancient impartial game believed to have originated in China. In 1901, Charles Bouton published the complete mathematical theory of Nim, introducing the concept of XOR addition.",
            realWorldApps = "Combinatorial game theory, compiler register allocation, and routing optimization in packet-switched networks."
        ),
        GameDef(
            id = "hanoi_tower",
            title = "Tower of Hanoi",
            category = GameCategory.PUZZLES,
            difficulty = Difficulty.HARD,
            description = "The classic recursive puzzle. Move the entire stack of disks from the first peg to the third peg without putting a larger disk on top of a smaller one.",
            instructions = "1. Drag or tap disks to move them between the 3 pegs.\n2. Rule 1: Move only one disk at a time.\n3. Rule 2: A disk can only be placed on a larger disk or an empty peg.\n4. Click 'Auto Solve' to watch the recursive solver execute the optimal path in 2^n - 1 moves!",
            durationMinutes = 5,
            concept = "Mathematical Induction and Recursion",
            tags = listOf("Recursion", "Induction", "Hanoi"),
            history = "Invented by the French mathematician Édouard Lucas in 1883, accompanied by a legend of a mystical temple where priests solve a 64-disk puzzle to end the universe.",
            realWorldApps = "Memory management, call stack handling in programming languages, and tree traversal algorithms."
        ),
        GameDef(
            id = "lights_out",
            title = "Lights Out Solver",
            category = GameCategory.PUZZLES,
            difficulty = Difficulty.HARD,
            description = "Turn off all the lights in a 3x3 grid! Toggling a light toggles itself and its horizontal and vertical neighbors. Use our linear algebra solver if you get stuck.",
            instructions = "1. Tap squares in the grid to toggle their states.\n2. Toggling a square flips its state and the states of all cardinally adjacent squares.\n3. The goal is to turn all lights completely off.\n4. Click 'Show Solver Hint' to see the exact clicks needed, computed using Gaussian Elimination!",
            durationMinutes = 5,
            concept = "Linear Equations over the Galois Field GF(2)",
            tags = listOf("Linear Algebra", "GF(2)", "Gaussian Elimination"),
            history = "Released as a handheld electronic game by Tiger Electronics in 1995. Its underlying mathematical structure forms a beautiful linear algebra vector space.",
            realWorldApps = "Error-correcting codes, cryptography (like AES S-Box transformations), and digital cellular transmissions."
        ),
        GameDef(
            id = "gray_code",
            title = "Gray Code Guess",
            category = GameCategory.LOGIC,
            difficulty = Difficulty.MEDIUM,
            description = "Observe a sequence of numbers where adjacent values differ in exactly one binary digit. Let the wizard decode your choice!",
            instructions = "1. Choose a number from 0 to 15.\n2. We will present 4 yes/no questions based on Gray code partition subsets.\n3. Tap 'Yes' or 'No' based on whether your number appears on the card.\n4. At the end, the Gray-to-Binary XOR converter will instantly pinpoint your exact number!",
            durationMinutes = 3,
            concept = "Reflected Binary Codes (Gray Code)",
            tags = listOf("Gray Code", "XOR", "Coding Theory"),
            history = "Patented by Frank Gray of Bell Labs in 1953, the Gray code prevents spurious transitions in mechanical rotary encoders.",
            realWorldApps = "Analog-to-digital converters, error correction in television broadcasts, and genetic algorithm chromosome cross-over representation."
        ),
        GameDef(
            id = "fifteen_puzzle",
            title = "15-Tile Slide Puzzle",
            category = GameCategory.PUZZLES,
            difficulty = Difficulty.HARD,
            description = "Arrange the tiles 1-15 into numerical order. The puzzle guarantees solvability by checking the permutation inversion parity.",
            instructions = "1. Tap on tiles adjacent to the empty space to slide them.\n2. Arrange the tiles in order from 1 to 15, with the empty space in the bottom right corner.\n3. The initial board is generated randomly but mathematically verified to be solvable (not all random setups are!)",
            durationMinutes = 5,
            concept = "Permutation Parity and Inversion Count",
            tags = listOf("Slide", "Parity", "Solvability"),
            history = "Invented by Noyes Palmer Chapman in the 1870s, it triggered a worldwide craze. Mathematicians Sam Loyd and Johnson proved that half of all starting states are mathematically unsolvable.",
            realWorldApps = "Pathfinding algorithms (like A* search) in artificial intelligence and robotics navigation."
        ),
        GameDef(
            id = "river_crossing",
            title = "River Crossing Solver",
            category = GameCategory.LOGIC,
            difficulty = Difficulty.MEDIUM,
            description = "Help the farmer transport a wolf, a goat, and a cabbage across the river. But beware! Unattended goats eat cabbage, and wolves eat goats.",
            instructions = "1. Tap items to load them onto the boat with the farmer.\n2. Click 'Cross River' to sail to the other bank.\n3. Ensure you never leave the wolf & goat, or the goat & cabbage alone together on either bank.\n4. Tap 'Get BFS Hint' to see the shortest path of safe states calculated using graph search!",
            durationMinutes = 4,
            concept = "State Space Search and Breadth-First Search (BFS)",
            tags = listOf("Graph Theory", "BFS", "State Space"),
            history = "This puzzle dates back to the Alcuin of York manuscripts in the 9th century, designed to sharpen logical thinking in young scholars.",
            realWorldApps = "Automated AI planning, network routing protocols, and compiling constraint solvers."
        ),
        GameDef(
            id = "domino_prediction",
            title = "Domino Predictor",
            category = GameCategory.MIND_READING,
            difficulty = Difficulty.MEDIUM,
            description = "A mathematical domino trick. Lay out a chain of dominoes and hide one, and the app will predict the exact endpoints of your chain!",
            instructions = "1. We will generate a standard set of dominoes.\n2. Choose any single domino to 'hide' in your hand.\n3. We will form a matching chain with the remaining dominoes.\n4. We will predict the exact left and right numbers of your completed chain, which matches your hidden domino's faces!",
            durationMinutes = 3,
            concept = "Eulerian Paths and Closed Loop Invariants",
            tags = listOf("Graph Theory", "Eulerian", "Invariants"),
            history = "First published in mathematical puzzle journals in France, this trick demonstrates that a full set of dominoes forms a connected graph where every node has an even degree, guaranteeing an Eulerian cycle.",
            realWorldApps = "Genome sequence assembly, circuit board drilling pathways, and mail delivery route planning."
        ),
        GameDef(
            id = "animal_guess",
            title = "Secret Animal Predictor",
            category = GameCategory.LOGIC,
            difficulty = Difficulty.MEDIUM,
            description = "Think of any animal! The app's mathematical decision tree will ask questions and guess your animal, expanding its knowledge base dynamically if it fails!",
            instructions = "1. Think of any animal (e.g., Lion, Penguin, Dolphin).\n2. Answer the questions honestly with 'Yes' or 'No'.\n3. If the app guesses correctly, the machine wins! If it fails, teach it a new question to expand its binary decision tree.",
            durationMinutes = 4,
            concept = "Binary Decision Trees and Machine Learning Splay",
            tags = listOf("AI", "Decision Tree", "Machine Learning"),
            history = "This game represents the earliest form of expert systems and artificial intelligence developed in the 1960s to model human classification patterns.",
            realWorldApps = "Medical diagnostic trees, customer support automated flows, and spam filtering classifiers."
        )
    )

    fun getGameById(id: String): GameDef? {
        return games.firstOrNull { it.id == id }
    }
}
